import type { LucideIcon } from 'lucide-react'
import {
  Activity,
  AlarmClock,
  Archive,
  BadgeDollarSign,
  BarChart3,
  Blocks,
  BookMarked,
  BookOpen,
  BookText,
  Bookmark,
  Bot,
  Box,
  Boxes,
  Braces,
  Brain,
  Briefcase,
  Brush,
  Bug,
  Building2,
  Calendar,
  CalendarDays,
  Camera,
  Car,
  ChartNoAxesCombined,
  CheckCircle2,
  ClipboardList,
  Clock,
  Cloud,
  Code2,
  CodeXml,
  Coffee,
  Compass,
  Cpu,
  CreditCard,
  Database,
  Download,
  Dumbbell,
  FileArchive,
  FileCode,
  Files,
  FileText,
  Film,
  Fingerprint,
  Folder,
  Frame,
  Gamepad2,
  Gift,
  GitBranch,
  Github,
  Globe,
  GraduationCap,
  HardDrive,
  Headphones,
  Heart,
  Home,
  Image,
  Kanban,
  KeyRound,
  Landmark,
  Layers,
  Layout,
  Leaf,
  Library,
  Lightbulb,
  Link,
  ListChecks,
  Lock,
  Mail,
  Map,
  MapPin,
  MessageCircle,
  Mic,
  Music,
  Network,
  Newspaper,
  Notebook,
  Package,
  Paintbrush,
  Palette,
  PenLine,
  PenTool,
  Plane,
  Podcast,
  Presentation,
  Radio,
  Receipt,
  Rocket,
  ScrollText,
  Server,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  Ship,
  ShoppingBag,
  ShoppingCart,
  Shapes,
  Smile,
  Sparkles,
  Star,
  Stethoscope,
  StickyNote,
  Tag,
  Target,
  Terminal,
  Timer,
  Train,
  TrendingUp,
  Trophy,
  UploadCloud,
  Users,
  Utensils,
  Video,
  Wallet,
  Webhook,
  Wifi,
  Wrench,
  Zap,
} from 'lucide-react'

export const categoryIconMap: Record<string, LucideIcon> = {
  // 基础
  BookmarkIcon: Bookmark,
  FolderIcon: Folder,
  StarIcon: Star,
  HeartIcon: Heart,
  ArchiveIcon: Archive,
  TagIcon: Tag,
  PackageIcon: Package,
  BoxIcon: Box,
  BoxesIcon: Boxes,
  // 开发
  CodeIcon: Code2,
  CodeXmlIcon: CodeXml,
  BracesIcon: Braces,
  FileCodeIcon: FileCode,
  TerminalIcon: Terminal,
  DatabaseIcon: Database,
  ServerIcon: Server,
  GithubIcon: Github,
  GitBranchIcon: GitBranch,
  WebhookIcon: Webhook,
  BugIcon: Bug,
  CpuIcon: Cpu,
  NetworkIcon: Network,
  BlocksIcon: Blocks,
  // AI
  BotIcon: Bot,
  BrainIcon: Brain,
  SparklesIcon: Sparkles,
  // 设计
  PaletteIcon: Palette,
  LayoutIcon: Layout,
  PaintbrushIcon: Paintbrush,
  BrushIcon: Brush,
  PenToolIcon: PenTool,
  ShapesIcon: Shapes,
  LayersIcon: Layers,
  ImageIcon: Image,
  FrameIcon: Frame,
  SmileIcon: Smile,
  // 效率
  ZapIcon: Zap,
  TargetIcon: Target,
  CalendarIcon: Calendar,
  CalendarDaysIcon: CalendarDays,
  ClockIcon: Clock,
  TimerIcon: Timer,
  AlarmClockIcon: AlarmClock,
  ListChecksIcon: ListChecks,
  ClipboardListIcon: ClipboardList,
  CheckCircleIcon: CheckCircle2,
  KanbanIcon: Kanban,
  WrenchIcon: Wrench,
  SettingsIcon: Settings,
  // 内容
  BookOpenIcon: BookOpen,
  BookMarkedIcon: BookMarked,
  BookTextIcon: BookText,
  LibraryIcon: Library,
  GraduationCapIcon: GraduationCap,
  ScrollTextIcon: ScrollText,
  FileTextIcon: FileText,
  FilesIcon: Files,
  FileArchiveIcon: FileArchive,
  StickyNoteIcon: StickyNote,
  NotebookIcon: Notebook,
  PenLineIcon: PenLine,
  NewspaperIcon: Newspaper,
  VideoIcon: Video,
  FilmIcon: Film,
  MusicIcon: Music,
  PodcastIcon: Podcast,
  HeadphonesIcon: Headphones,
  MicIcon: Mic,
  RadioIcon: Radio,
  CameraIcon: Camera,
  // 社交
  UsersIcon: Users,
  MessageCircleIcon: MessageCircle,
  MailIcon: Mail,
  ShareIcon: Share2,
  LinkIcon: Link,
  // 商业
  ShoppingBagIcon: ShoppingBag,
  ShoppingCartIcon: ShoppingCart,
  CreditCardIcon: CreditCard,
  WalletIcon: Wallet,
  ReceiptIcon: Receipt,
  BadgeDollarSignIcon: BadgeDollarSign,
  BarChartIcon: BarChart3,
  ChartIcon: ChartNoAxesCombined,
  TrendingUpIcon: TrendingUp,
  BriefcaseIcon: Briefcase,
  BuildingIcon: Building2,
  LandmarkIcon: Landmark,
  PresentationIcon: Presentation,
  // 安全与云
  LockIcon: Lock,
  ShieldIcon: Shield,
  ShieldCheckIcon: ShieldCheck,
  KeyIcon: KeyRound,
  FingerprintIcon: Fingerprint,
  CloudIcon: Cloud,
  HardDriveIcon: HardDrive,
  WifiIcon: Wifi,
  DownloadIcon: Download,
  UploadCloudIcon: UploadCloud,
  // 生活与其他
  GlobeIcon: Globe,
  MapIcon: Map,
  MapPinIcon: MapPin,
  CompassIcon: Compass,
  RocketIcon: Rocket,
  LightbulbIcon: Lightbulb,
  TrophyIcon: Trophy,
  GamepadIcon: Gamepad2,
  ActivityIcon: Activity,
  DumbbellIcon: Dumbbell,
  StethoscopeIcon: Stethoscope,
  LeafIcon: Leaf,
  GiftIcon: Gift,
  CoffeeIcon: Coffee,
  UtensilsIcon: Utensils,
  PlaneIcon: Plane,
  CarIcon: Car,
  TrainIcon: Train,
  ShipIcon: Ship,
  HomeIcon: Home,
}

export const DefaultCategoryIcon = Bookmark
export const FolderCategoryIcon = Folder
